# Generated by Django 6.0.4 on 2026-04-30 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.CharField(default='', max_length=255)),
                ('coupon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_refundable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_detail', models.JSONField(verbose_name='Detail')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('pawapay', 'Pawapay'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('collection', 'Collection'), ('disbursement', 'Disbursement'), ('refund', 'Refund')], default='collection', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='payment_logos', verbose_name='Payment Logo')),
                ('short_name', models.CharField(max_length=15, verbose_name='Short name')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('payment_class', models.CharField(choices=[('phone_number', 'Phone Number'), ('credit_card', 'Credit Card'), ('master_card', 'Master Card')], max_length=20, verbose_name='Payment Class')),
                ('payment_provider', models.CharField(choices=[('orange_cameroon', 'Orange Cameroon'), ('mtn_cameroon', 'MTN Cameroon')], max_length=20, verbose_name='Payment Provider')),
                ('deposit_fee_percentage', models.FloatField(default=0.0)),
                ('deposit_fee_fixed', models.FloatField(default=0.0)),
                ('platform_deposit_fee_percentage', models.FloatField(default=0.0)),
                ('platform_deposit_fee_fixed', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed')], default='pending', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='kunshort_payment.paymenttransaction')),
            ],
            options={
                'verbose_name_plural': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='kunshort_payment.paymenttransaction')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kunshort_payment.paymenttype'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=255)),
                ('detail', models.JSONField(verbose_name='Detail')),
                ('is_default', models.BooleanField(default=False)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='kunshort_payment.paymenttype')),
            ],
            options={
                'unique_together': {('user_id', 'payment_type', 'detail')},
            },
        ),
    ]
