# Generated by Django 6.0.5 on 2026-05-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kunshort_payment", "0003_rename_service_and_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="reference_type",
            field=models.CharField(max_length=255),
        ),
    ]
